### ISSUE TITLE
Text object clipping clashes with typeface geoemetry in some scenarios

### ISSUE THREAD

**Issue by RomanHargrave** [uxbox/uxbox#1231]
**Describe the bug**
In a text object of fixed dimension, changing to right alignment may result in portions of the type being cut off.

**To Reproduce**
1. Create a text object and set typeface to *Cormorant Garamond*, variant *italic* (reg. weight)
2. Set contents of text object to something such as `~12:30` (what was used in this case, any text will likely work)
2. Resize text object to a fixed size
3. Select ragged right text alignment
4. Observe that rightmost letterform is cut off

**Expected behavior**
Right-most letterform will not be cut off

**Screenshots**
![the text "~12:30" in italics with the "0" being partially obscured](https://i.imgur.com/VBy7BBr.png)

**Desktop (please complete the following information):**

-   OS: Linux
-   Browser: Chrome

**Environment (please complete the following information):**
SaaS

**Comment by myfunnyandy** [comment]
Thanks for raising the issue. We will manage it at Taiga from here https://tree.taiga.io/project/penpot/issue/2054

**Comment by garrett** [comment]
I'm not sure if it's related, but I also have text clipping issues on the right when _exporting_ a document, even when it looks fine within the document itself. This is with the sans serif fonts "Red Hat Display" and "Red Hat Text" in some mockups I've been working on for the Cockpit project within Penpot.

At first, I thought it might be Firefox (export from Firefox):

![storage-format-modal](https://user-images.githubusercontent.com/10246/135472238-63060ca8-a286-4371-ad31-f0a617060fc5.png)

So I also tried Chromium and had similar results (it isn't quite as bad, but it is still aggressively cropped):

![storage-format-modal (1)](https://user-images.githubusercontent.com/10246/135472332-7f51b28d-b43f-4a60-92e5-4322d32fd3f8.png)

It's supposed to look like this (I resorted to a screenshot of Penpot itself within Firefox, which I then cropped to size):

![135458414-dbfcad49-607d-4c29-92ab-2ba2335be0c9](https://user-images.githubusercontent.com/10246/135472538-e0800a75-b516-4a8c-acc9-081ad9ccac44.png)

If I do a difference (which I then inverted in value) of the screenshot of Firefox versus the export from Firefox, I see that the font is rendered quite differently, which might be responsible for some of the clipping: 

![image](https://user-images.githubusercontent.com/10246/135473026-656f1161-6e3b-4d28-9d04-897d770bb0be.png)

Again, I'm unsure how much this might be related to clipping of text when rendering versus exporting, but as it's text clipping with font rendering, I figured it might be related. (We can move this to another issue if it's not.)

I tried exporting the file, but Penpot just shows a red "X", which I guess means it couldn't export due to some error?

While it's probably not as useful, here's a link to the preview, however: https://design.penpot.app/#/view/691cadb0-21e4-11ec-985f-f08c5eccf3df?page-id=691cadb1-21e4-11ec-985f-f08c5eccf3df&index=0&share-id=338ad580-21fa-11ec-985f-f08c5eccf3df
