### ISSUE TITLE
No non-docker deployment instructions in the readme.

### ISSUE THREAD

**Issue by duaneking** [uxbox/uxbox#1376]
**Describe the bug**
A link to the deployment instructions should be included in the readme, if the steps are not listed directly.

**To Reproduce**
Look in the project readme; no effort to allow others to deploy this seems to have been made unless docker is used.  The link that does exit is not clear to its intent, and only lists docker instructions. What about non-docker deployments?  Not everybody wants to take on the added cost of docker. This may be a minor thing to some. but it shows the priorities of this project; is it about your production subscription service, or is it about the open source community?

**Expected behavior**
A clear and concise deployment strategy outlined for common scenarios that do not use docker or depend on a specific docker image. Show us that you are not only focused on making money at the expense of the open source community.

**Environment (please complete the following information):**
All versions and platforms.

**Comment by hirunatan** [comment]
Sorry, this is a meditated decission. Installing Penpot without docker is not a trivial task: there are quite a few services to install, configure and connect them with each other, with many small steps. If we published some guide to do it, we'll need to give support to a lot of use cases of different people. In the future it may be feasible, but for the moment we are a small company and still don't charge anything for it.

So we support only docker installation. A person who wants to install it by hand, or to do some distribution packaging, for example, could relatively easily guess how to do it by looking at the Dockerfile and docker-compose files.

**Comment by duaneking** [comment]
Well is this open source or not?

This sounds like the sort of response a for-profit company that has no real interest in supporting the open source community would say.  Are you wanting to support the open source community? Or are you trying to sell licenses to docker images?

**Comment by niwinz** [comment]
As @hirunatan said, we are small company working and giving this software for free with open source license, and right now we are working on other features and we don't have resources right now to maintain and write custom installation process documentation. Besides that there are too many custom installation variants, I'm pretty sure that if we write guide for Debian, there will be people asking for Ubuntu or Fedora or Centos...

In any case, looks like we have some misunderstanding here with open-source concept. The docker images are open, the Dockerfile's (source of docker images) are also open. Looks like no one want sell you a docker image license...
We provide the docker approach for Penpot installation. But there are too many ways to install it. If our current approach does not satisfies you, you can contribute back and write the guide yourself, using your own approach. This is the authentic open-source spirit, contributing instead of asking/requiring. There some links to docker images and build scripts (that are open-source):

- https://github.com/penpot/penpot/tree/develop/docker/images
- https://github.com/penpot/penpot/blob/develop/frontend/scripts/build
- https://github.com/penpot/penpot/blob/develop/backend/scripts/build
- https://github.com/penpot/penpot/blob/develop/exporter/scripts/build

I invite you to write the custom non-docker installation guide, and contribute it to the open-source community in the same spirit as we do it: releasing Penpot as open-source software and providing an installation guide (in this case using docker, one of many ways to install it)

**Comment by duaneking** [comment]
I didn't misunderstand you; I'm having a side conversation with Paula.

You're also a for-profit company, so there is definite reason for concern.
