### ISSUE TITLE
Text alignment inconsistent

### ISSUE THREAD

**Issue by NicolasLeboeuf** [uxbox/uxbox#1402]
**Describe the bug**
When I set the alignment of a text element and change the text, the alignment is not properly respected.

**To Reproduce**
1.  Create a text element, i.e "8.45 €"
2. Align it to right
3. Remove characters and replace the text with a smaller or larger one. The new text is not typed from right to left.
4. The text is no longer properly aligned.

**Expected behavior**
The text typing direction fits with the text element alignement: if the text element is set to "align to right", the right side of the element should never move.

It should do the same for center alignement, it has the same issue.

**Screenshots**
1. I'm starting with this data, and want to change the second "8.45 €" to "19%". It is a copy of the first one, and is right aligned.
![image](https://user-images.githubusercontent.com/62602652/145556066-f7a25963-45e3-464e-b94d-ed7fd37427c0.png)
2. I remove the text, the right side has moved to the left
![image](https://user-images.githubusercontent.com/62602652/145556190-5c6abf99-8c19-4eb9-8436-abb5e23df2b9.png)
3. New data
    1. 
![image](https://user-images.githubusercontent.com/62602652/145556318-017431b3-a17e-488d-ada1-707681f54421.png)
    2. 
![image](https://user-images.githubusercontent.com/62602652/145556351-c7f6d468-a3a5-452d-a183-bd400a4586c6.png)
4. My new element is no longer aligned with the header
![image](https://user-images.githubusercontent.com/62602652/145556261-cec757a5-5039-405d-978f-b8f7e6711b3d.png)

**Desktop (please complete the following information):**

-   OS: Win 10
-   Browser Chrome
-   Version 96

**Environment (please complete the following information):**
SAAS

**Additional context**
For comparison with Adobe Xd:

![image](https://user-images.githubusercontent.com/62602652/145556900-28529f32-054f-45c1-bd53-f0859f3dcc57.png)
and then
![image](https://user-images.githubusercontent.com/62602652/145556922-c20d9890-cd01-4094-ba46-e719afc3e030.png)

**Comment by EvaMarco** [comment]
Hello @NicolasLeboeuf. 
If you want your text to grow from right to left you can change the orientation of it using RTL button in the text formatting area. 

![Like this](https://user-images.githubusercontent.com/48989967/146801520-4ba95c54-4155-4dc1-b39b-b3948f42b855.png)


Here it's a small gif showing how it works. 
![Video](https://user-images.githubusercontent.com/48989967/146801510-fc245fdc-86a5-4abd-b4b3-0da990219c52.gif)

Tell me if this fixes your issue or you need something more.

**Comment by NicolasLeboeuf** [comment]
Oh, I didn't see this button.

The "left to right" one is not highlighted by default, so I didn't see it, contrarily to others. Maybe an enhancement?

edit: same for text-align btw

**Comment by EvaMarco** [comment]
Hello again @NicolasLeboeuf, today I came with another solution to your problem and a bit of explanation. 

![text-alignement](https://user-images.githubusercontent.com/48989967/146897724-0acb2f91-ed93-457a-a6c5-ad569f67f657.gif)

In this video, I manage to do the same without using RTL which is not the best practice to get what you need. 
 
The key was using align to right and fixed content width.

![Alignement text](https://user-images.githubusercontent.com/48989967/146898245-5f598829-4b7c-478e-921e-752fe17eacd8.png)

With fixed property, the text box always has the same width and avoids what happened to you. 
In the future versión, we want to improve autolayout and allow alignment to right and auto width property activated at the same time.

There is no RTL/LTR option highlighted by default because is not set by default. That means that direction will be determined by the user system but still have the option to force it.

**Comment by NicolasLeboeuf** [comment]
Ok for me, thanks.
