### ISSUE TITLE
confusing names. "pages and artboards" should be "documents and pages"

### ISSUE THREAD

**Issue by milahu** [uxbox/uxbox#1455]
when i export to pdf, only one "page" is exported, and the "artboards" become pages

why not say "documents" and "pages" in the first place?

use case:
im using penpot to write a research paper, targeting screen and print

**Comment by elhombretecla** [comment]
Hi @milahu thanks for your feedback :)

It is a good point. In other hand, let's think that an artboard could be used for more different cases than as a page (i.e. container for an icon, ui element, etc...)

Anyway, we have a pending conversation about this in order to do this naming less confusing.

**Comment by elhombretecla** [comment]
We've been talking and working around this issue. We also developed related functionalities like "Nested Boards" (will be available soon) around this topic.

The conclusion is that "Pages" and "Artboards, Boards, Frames,..." are a standard wording in design and prototyping tools so we are going to keep "Pages" and "Boards" for Penpot.

Thank you so much!
