### ISSUE TITLE
Docker : Backend does not stay up

### ISSUE THREAD

**Issue by slfhstr** [uxbox/uxbox#1565]
**Describe the bug**
Running "stock" docker-compose.yaml and commands from docs
All containers start initially
Within some seconds, backend fails.

**Screenshots**
<img width="1477" alt="Screenshot 2022-02-09 at 09 28 09" src="https://user-images.githubusercontent.com/28682881/153167600-9a418af3-d2cd-45a0-8092-d68774f8fa11.png">
NB : no interaction with system - just fails after some time

**Environment (please complete the following information):**
self-hosted instance.

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: Ubuntu 20.04

Also provide Docker commands or docker-compose file if possible and if proceed.x

-   Docker / Docker-compose Version: 
```
root@-:~/penpot# docker --version
Docker version 20.10.12, build e91ed57
root@-:~/penpot# docker-compose --version
docker-compose version 1.28.5, build c4eb3a1f
```

From config.env (the rest as downloaded)
```
# Should be set to the public domain where penpot is going to be served.
PENPOT_PUBLIC_URI=http://app.domain.tld

# Temporal workaround because of bad builtin default
PENPOT_HTTP_SERVER_HOST=0.0.0.0
```

**Comment by niwinz** [comment]
I will need the logs of the backend container, without that I have no idea what is happening

**Comment by slfhstr** [comment]
Seem to PG auth
```
+ exec /usr/lib/jvm/openjdk16/bin/java -jar penpot.jar -m app.main
[2022-02-09 09:21:43.392] I app.metrics - action="initialize metrics"
[2022-02-09 09:21:44.787] I app.db - action="initialize connection pool" name="main" uri="postgresql://penpot-postgres/penpot"
Execution error (PSQLException) at org.postgresql.core.v3.ConnectionFactoryImpl/doAuthentication (ConnectionFactoryImpl.java:623).
FATAL: password authentication failed for user "penpot"
Full report at:
/tmp/clojure-2255237112952402259.edn
```

**Comment by slfhstr** [comment]
I reverted the PG password to default
Backend stays up (for now anyway)
Frontend comes up 
Is pg password in config.env fully supported (not hard-coded somewhere else)?!
Bizarre that this one change would make a difference.

**Comment by slfhstr** [comment]
user password registration does not seem to work using `docker exec -ti penpot_penpot-backend_1 ./manage.sh create-profile`
3 times ran command with `User created successfully.` response, none of them work.

EDIT : mentioning it in this thread not a new one because it smells to me that password handling is screwed.

**Comment by niwinz** [comment]
> I reverted the PG password to default Backend stays up (for now anyway) Frontend comes up Is pg password in config.env fully supported (not hard-coded somewhere else)?! Bizarre that this one change would make a difference.

I'm not clearly understand the question. If you want different password, change it on the database and on the backend environment variables. Nothing in penpot is restricting this. And you can manage the password as you want, on the end penpot need to know it using environment variables. You can set it on config.env or using any other mechanism you have to pass environment variables to penpot.

**Comment by niwinz** [comment]
> user password registration does not seem to work using `docker exec -ti penpot_penpot-backend_1 ./manage.sh create-profile` 3 times ran command with `User created successfully.` response, none of them work.
> 
> EDIT : mentioning it in this thread not a new one because it smells to me that password handling is screwed.

Are you running on different domain than `localhost` without https? If so, this is the cause. The `localhost` domain is considered secure on browsers and they don't require https. If penpot is served on different domain but don't using https the session cookie is not sent correctly because browsers restrict this.

For enable NON https access on  domains different than `localhost` you need to put the `disable-secure-session-cookies` on the `PENPOT_FLAGS` environment variable. This will set session cookies without the secure flag.

**Comment by slfhstr** [comment]
I guess it's a documentation issue
Docker is about making simple installation and simple running.
Yes, config.env allows you to change pg password.
But nothing in config.env to say do anything else.
And nothing in `https://help.penpot.app/technical-guide/configuration/`
After your message, I check docker-compose.yaml
Oooh look, right at the bottom there is a "hard-coded" default pg password.
Users expect to change config.env
They don't expect to change docker-compose.yaml : too easy to break something.
If they should do so, then users should be told :
`change it here and then change it there`
I understand you will not agree that this is hard-coded password.
But unless help docs explain, it is de facto hard-coded.

Thanks for your help.
I liked your hosted SaaS instance, so trying it self-hosted.
I will close this now.
Thanks again.

**Comment by niwinz** [comment]
> I guess it's a documentation issue Docker is about making simple installation and simple running. Yes, config.env allows you to change pg password. But nothing in config.env to say do anything else. And nothing in `https://help.penpot.app/technical-guide/configuration/` After your message, I check docker-compose.yaml Oooh look, right at the bottom there is a "hard-coded" default pg password. Users expect to change config.env They don't expect to change docker-compose.yaml : too easy to break something. If they should do so, then users should be told : `change it here and then change it there` I understand you will not agree that this is hard-coded password. But unless help docs explain, it is de facto hard-coded.
> 
> Thanks for your help. I liked your hosted SaaS instance, so trying it self-hosted. I will close this now. Thanks again.

Glad to help!

To get some additional context:
On the end docker is pretty complex piece of software, and managing it can be complicated. From the user perspective for basic usage, yo don't need to change the password because, changing it as-is, does not increase security, because the same password still is available on the file. And postgresql is only accesible from the penpot container, so the normal user does not need to mess with this at all.

The documentation does not explains this, because this is postgresql/docker related and we can't explain every envolved piece, imagine having to document how to configure nginx, redis, postgres, etc... in the penpot documentation; Is literally makes imposible and redundant. We are small team with small resources and we do the best documenting the penpot part, I know we can do it beter but for now is that we have. Any improvements and help is welcome.

For now, `config.env` is penpot configuration file and in the `docker-compose.yml` you have configuration of the rest of the services used by penpot. Maybe using a single file for them all can be a good idea. 
But, in any case, there is a good recommendation to set a fixed penpot image version (instead of using `latest`) and update explicitly that value on each release. Having it in `latest`, can cause that some release come with some config changes you didn't applied and the service becomes unavailable when you may don't have time to looking on it... and for this you sill need to modify the `docker-compose.yml` file.

**Comment by slfhstr** [comment]
Thank you for the explanation.
Yes, I appreciate it is complex.
And I'm a user, not dumb user, but not developer.
So I appreciate all your help.

I see a lot of 'default' passwords in docker files.
As a user, my first reaction is `that's not secure`
Not understanding it maybe doesn't matter.
While it seems not industry practice, it seems to be better to set the default password to `pg-cRt1M84` or similar.
Then user sees no reason to change it.

Thanks for the advice about `latest`
