### ISSUE TITLE
Are there plans to support Autolayout and Figma file imports

### ISSUE THREAD

**Issue by Carlosfengv** [uxbox/uxbox#1691]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when (...)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by EsterLatorre** [comment]
Hello Carlos,

Nice suggestion! We're considering a similar approach to Auto layout and we're working on it at the moment. In case you are interested, you can see some details here: https://tree.taiga.io/project/penpot/us/2262

Regarding the Figma file imports, we are not currently supporting it but it is in the roadmap

Thanks!

**Comment by alexanderadam** [comment]
Just for completeness: the [Figma file import feature is on Taiga as well](https://tree.taiga.io/project/penpot/us/1469) (as well as [Sketch import](https://tree.taiga.io/project/penpot/us/1470) - see [issue 849](https://github.com/penpot/penpot/issues/849)).

**Comment by niwinz** [comment]
This issue looks like reports more than one thing so tracking it is a bit complicated.
Autolayout is already in development and probably will land on the 1.16.x release.

I close this issue, If something from this issue is not covered, please open a separate issue per bug/feature.
In any case, thanks for open the discussion and reporting this.

**Comment by jcklpe** [comment]
Update on this subject can be found here: https://community.penpot.app/t/what-are-penpot-plans-for-autolayout/112
