### ISSUE TITLE
verification of email not working

### ISSUE THREAD

**Issue by thefonso** [uxbox/uxbox#2249]
"Forgot password?" 
we'll send you an email with instructions

page requires "Profile is not verified, please verify profile before continue"

The app does not send me a email verification in my email. So there is not a way to reset the account.

Why is there a "give us your email before you can use the app" wall in the first place? (That is infuriating)

I am locked out on my first try of installing the app.

By the way I'm a senior level software engineer who has an interest in opensource and design tools...I found you today while looking for alternatives to Figma)

Suggestion: TAKE THE EMAIL LOGIN OFF

Let your users use the app. and then submit their emails in user creation for some extra features. 

UPDATE: 

Used the install with Docker instructions on the Readme here ... https://help.penpot.app/technical-guide/getting-started/#install-with-docker

**Comment by superalex** [comment]
Hello @thefonso,

Thank you very much for your feedback, we will consider it t.

About your issue, what method are you using to install penpot?. If you are following the [docker guide](https://help.penpot.app/technical-guide/getting-started/) the installation you need some extra steps to have smtp working
- https://help.penpot.app/technical-guide/getting-started/#configuration
- https://help.penpot.app/technical-guide/configuration/#email-(smtp)

**Comment by chetan** [comment]
Not entirely sure if this is the same problem, but I had a related issue with the out-of-the-box installation via docker. According to the docs: 

> By default, when no SMTP (email) is configured, the email will be printed to the console, which means that the emails will be shown in the stdout. If you have an SMTP service, uncomment the appropiate settings section in docker-compose.yml and configure those environment variables.

With the default `config.env` which has `PENPOT_SMTP_ENABLED=false`, the emails are not printed to STDOUT. Instead I'm seeing repeated errors trying to deliver to `localhost:25`:

```
penpot-penpot-backend-1  | com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout 30000
penpot-penpot-backend-1  |     at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2210) ~[penpot.jar:?]
penpot-penpot-backend-1  |     at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:722) ~[penpot.jar:?]
penpot-penpot-backend-1  |     at jakarta.mail.Service.connect(Service.java:342) ~[penpot.jar:?]
```

**Comment by niwinz** [comment]
for disable smpt you need to use `PENPOT_FLAGS=$PENPOT_FLAGS disable-smtp`

The `PENPOT_SMTP_ENABLED` env is deprecated long ago and now removed in the latest versions.

**Comment by Gabsha** [comment]
Hi! I ran in a similar issue today (backend version `1.15.2-beta-7851-g2cb8e7b98`).

Just like @chetan , I could not manage to disable SMTP with neither `PENPOT_SMTP_ENABLED=false` flag (part of the config.env file) nor the `PENPOT_FLAGS=$PENPOT_FLAGS disable-smtp`. The backend kept trying to connect to an smtp server.

Ended up using Mailcatcher to trap emails in the meantime, and since the SMTP connection was successful, the email were also printed to stdout.

**Comment by niwinz** [comment]
> 
> Suggestion: TAKE THE EMAIL LOGIN OFF
> 
> Let your users use the app. and then submit their emails in user creation for some extra features.

I think this tone and the caps are not necessary. You are thinking just on your needs. If you are using penpot alone on your laptop, this is reasonable, but if you are small company using it, it need proper email verification and other security properties are needed. So just putting it off is not an option.

@Gabsha 

On the other hand, the default installation should have the email verification disabled by default (when no smtp account), but I guess there are some bugs here and we will look on ASAP.

**Comment by niwinz** [comment]
After digging into it, I think is a bad default configuration. Let me explain:

1. take the email off: this can be done using the `enable-insecure-register`; (i will add it to the default configuration on the config.env file)
2. for disable smtp we need to use flags (I will update the config.env)
3. if you want to log emails to console you will need to use the `enable-log-emails` flag (this will change in the next release, since next minor release if smtp is disabled, the emails are printed by default)

**Comment by chetan** [comment]
@niwinz thank you. Confirming that the following worked for me:

```
PENPOT_FLAGS="enable-registration enable-login enable-insecure-register enable-log-emails disable-smtp"
```

I can now create the first user via signup.

The flags are probably a bit redundant for the initial signup but it appears that connection errors are still logged when trying to then add additional users to a team.

**Comment by Gabsha** [comment]
@niwinz Thank you for looking into it. 
Here are the flag's I used
```
PENPOT_FLAGS="enable-login enable-log-invitation-tokens enable-log-emails disable-registration disable-smtp"
```
I realize I didn't mention that the email I was trying to log/catch was the **invitation email** to add a user to a team, not the signup one, as I created users using the `manage.sh create-profile` script.

I tried adding the `enable-insecure-register`, but it didn't have any impact on the invitation emails.

**Comment by thefonso** [comment]
> I think this tone and the caps are not necessary.

@niwinz  Apologies...didn't mean to seem like I was shouting ^_^. 

>On the other hand, the default installation should have the email verification disabled by default (when no smtp account), but I guess there are some bugs here and we will look on ASAP.

Thank you Thank you, Yes, this would be great. As I would love to be able to suggest this tool to my company. But I need to see it workable in an "individual mode" first.

Thank you for your hard work!

**Comment by kumarmo2** [comment]
> After digging into it, I think is a bad default configuration. Let me explain:
> 
> 1. take the email off: this can be done using the `enable-insecure-register`; (i will add it to the default configuration on the config.env file)
> 2. for disable smtp we need to use flags (I will update the config.env)
> 3. if you want to log emails to console you will need to use the `enable-log-emails` flag (this will change in the next release, since next minor release if smtp is disabled, the emails are printed by default)

Thank you so much. This worked for me. 

and Thanks again for the amazing work!

**Comment by easaw** [comment]
> You are thinking just on your needs.

Sorry but I have to agree with @thefonso on a basic level.

Running this locally or in production becomes very frustrating when the SMTP just doesn't work and isn't necessary, even when live, many other docker installs have required env variables that include a 'starter' or admin username and password, or a password is generated.

As the Docker setup creates a database, why not populate one row with a default email and password and
`is_active = true`?

Budibase and even CapRover have default accounts or passwords, because their developers assume that the the people using Docker to setup these apps have enough experience to either:

- create a new user,
- or change the default password.

Preventing that when probably 99% of people setting up are sys-admins or I.T. people, is at the very least bad user experience for the sake of overzealous "security".

In fact, IMHO it's worse that `enable-registration` is active by default, as that is more likely to be forgotten, than for an I.T. person to login with a default account and 'have' to change it.
At least with a default account, it isn't leaving the entire PenPot install wide open...

**Comment by niwinz** [comment]
I agree that the current approach is not the ideal, and we have plans to have an "admin" interface for manage (create, delete, modify), users on the on-premise. And I also agree that until now the situation was a bit problematic in some aspects.

But I also need to say that many things are fixed and improved and, with current defaults you can:
- start all container in **localhost**
- register a user without having smtp enabled

I checked it right now, and having an user. It has not taken me even 5 minutes, to have the entire environment up.

The `enable-registration` is active by default for you will be able to make the first registration without going public.
The SMPT is not required on the first startup, the registration is available without email verification and user invitations are printed on console (in some near future you will be able to copy the invitation link on the UI #2521 , and proceed with SMTP completely disabled)

But when you are going online, serve it to other users, you need to read the documentation to make it properly work: you have the option to use HTTPS, or set the flag: `disable-secure-session-cookies` for enable authentication on non secure environment.
