### ISSUE TITLE
Import from Figma

### ISSUE THREAD

**Issue by ahmaduxui** [uxbox/uxbox#2265]
Add the ability to import from Figma to Penpot

**Comment by Belikeoscar** [comment]
🤣I can see we are all on the run , looking for open source alternatives. I am open to contributing to this project too

**Comment by AstonJay** [comment]
🤣 Very true! I too am on the run😂 This might be an awesome project to contribute to.

**Comment by myfunnyandy** [comment]
Importing Figma files to Penpot is already in our plans (here the [story at Taiga](https://tree.taiga.io/project/penpot/us/1469)) and due to recent events it might happen sooner than expected :)

In the meantime, you can take a look and participate in some converstations that are taking place at the community about import from Figma and other tools:

- [https://community.penpot.app/t/feature-request-ability-to-import-sketch-adobe-xd-or-figma-files-into-penpot/418/2](https://community.penpot.app/t/feature-request-ability-to-import-sketch-adobe-xd-or-figma-files-into-penpot/418/2)
- [https://community.penpot.app/t/can-i-transfer-a-figma-project-to-penpot/276/2?u=myfunnyandy](https://community.penpot.app/t/can-i-transfer-a-figma-project-to-penpot/276/2?u=myfunnyandy)

**Comment by pm4rcin** [comment]
@myfunnyandy maybe pin the issue for the time being so people could easily see it because otherwise there could be new issues created regarding that?

**Comment by myfunnyandy** [comment]
@pm4rcin the number of "import from figma" requests have grown exponentially the latest days, so let's try this, why not :)

**Comment by Musiphilos** [comment]
I would upvote this aswell.

**Comment by myfunnyandy** [comment]
We've published an update at the community. Everyone is invited to join the conversation there: https://community.penpot.app/t/figma-file-importer/1684
