### ISSUE TITLE
Get a blank page when login https://penpot.app/

### ISSUE THREAD

**Issue by autumngao** [uxbox/uxbox#2301]
**To Reproduce**

1.  Go to main page of 'penpot.app'
2.  Click on 'Login'
3.  And you will get the follow page

![image](https://user-images.githubusercontent.com/6838877/191223846-cecc05f3-28e0-41c9-a51c-559546d8e7d8.png)

**Comment by myfunnyandy** [comment]
This is a known bug that we hope to fix soon: https://tree.taiga.io/project/penpot/issue/4127

The problem is that something is blocking [this javascript file](https://sdk.arengu.com/forms.js). It could be a plugin, a VPN or a firewall. You could try to avoid this problem on your side so you dont have to wait for us to publish the fix.

**Comment by autumngao** [comment]
> This is a known bug that we hope to fix soon: https://tree.taiga.io/project/penpot/issue/4127
> 
> The problem is that something is blocking [this javascript file](https://sdk.arengu.com/forms.js). It could be a plugin, a VPN or a firewall. You could try to avoid this problem on your side so you dont have to wait for us to publish the fix.

Thank you. I'll try.
