### ISSUE TITLE
Catching CTRL+S shortcut

### ISSUE THREAD

**Issue by LauraWebdev** [uxbox/uxbox#2314]
**Is your feature request related to a problem? Please describe.**
Since I'm transitioning from desktop based tools, I constantly press ctrl+s to save the current file (Because, as we all know, you should save often, so I do it after every few actions, and even if penpot doesn't need manual saving, it's still in my muscle memory). It would be neat if the editor wouldn't display the browsers "save webpage" modal.

**Describe the solution you'd like**
When pressing CTRL+S, prevent the default behavior of saving the editor website.

**Describe alternatives you've considered**
A browser plugin that automatically runs the following js code for the time being.
```js
document.addEventListener("keydown", function(e) {
  if (e.key === 's' && (navigator.platform.match("Mac") ? e.metaKey : e.ctrlKey)) {
    e.preventDefault();
  }
}, false);
```

**Comment by myfunnyandy** [comment]
Hi @LauraWebdev,

As a general rule, at the Penpot app we try not to interfere with the browser shortcuts. In this particular case It would be hard to justify to prevent the shortcut as there is no need for it because Penpot files are continually autosaving.

I totally understand the personal preference and we might take into consideration if we rethink how we deal with browser shortcuts and/or develop related user settings.

**Comment by LauraWebdev** [comment]
> Hi @LauraWebdev,
> 
> As a general rule, at the Penpot app we try not to interfere with the browser shortcuts. In this particular case It would be hard to justify to prevent the shortcut as there is no need for it because Penpot files are continually autosaving.
> 
> I totally understand the personal preference and we might take into consideration if we rethink how we deal with browser shortcuts and/or develop related user settings.

Hey there, I figured as much, considering there are no shortcuts that do that currently. I was thinking this was a special case, since it opens up a prompt that actively prevents work when pressed.

**Comment by expionage** [comment]
Hi, I ran across the same issue since I'm used to saving my work often across multiple software. To mitigate the disruption of the file/directory pop-up every time I do that, I used the below code, but would be great if this is integrated into the core product.

In mainfest.json:

```javascript
{
  "manifest_version": 2,
  "name": "PenPot Prevent Save",
  "version": "1.0",
  "description": "Prevent Save As Dialog in PenPot",
  "permissions": ["activeTab", "tabs", "*://*.penpot.app/*"],
  "background": {
    "scripts": ["content.js"],
    "persistent": false
  },
  "content_scripts": [
    {
      "matches": ["*://*.penpot.app/*"],
      "js": ["content.js"]
    }
  ]
}
```

In content.js:
```javascript
var injectedCode = `window.addEventListener('keydown', function(e) {
  if (e.ctrlKey && e.key === 's') {
    e.preventDefault();
  }
});`;

var script = document.createElement('script');
script.textContent = injectedCode;
(document.head||document.documentElement).appendChild(script);
script.parentNode.removeChild(script);
``` 

1. Create a browser extensions/plugin folder to store the above two files
2. Enable developer mode and "load unpacked" and navigate/point to this folder
3. Activate this browser extension
4. Reload the extension

This should disable the file/directory pop-up every time you hit CNTRL-S.

Hope this helps someone.
