### ISSUE TITLE
feature: guest comments

### ISSUE THREAD

**Issue by der-On** [uxbox/uxbox#2410]
### Is your feature request related to a problem? Please describe.

As an agency with many projects we cannot create accounts for all customers to comment on prototypes, simply because most people do not wan't to have yet another account and forgett credentials all the time. Comparable tools have the ability to let guests comment which is very valuable as we can gather feedback on prototypes quickly and easily.

### Describe the solution you'd like.

Provide the ability to create prototype share links that allow guest commenting. When creating a comment one must enter theire e-mail and name. This email is stored and used during the session. Notifications about new comments in that prototype or the created comments are also send to that email.

### Describe alternatives you've considered.

I've tried creating accounts for customers, but they either did not tried to join or got an error during the registration.

**Comment by EsterLatorre** [comment]
Hello der-On,

There is a reason why we don't allow this and it is security. Letting non-validated, non-registered users would be a gateaway for spam.

As a possible alternative, I suggest you edit the settings so that users that don't belong to the team can leave you comments: https://help.penpot.app/user-guide/view-mode/#viewmode-sharing

I hope this helps,
Cheers

**Comment by der-On** [comment]
@EsterLatorre I've heard in the latest podcast, that guest comments are existing now. Is that correct? If so, how can I enable them?

**Comment by honzito** [comment]
I understand, but still - it is not practical to create account for all clients, who have to comment the design. 

Ammount of spam can be reduced by:
  - allowing comments just to people with the link (I expect no one can gues the link)
  - allow just 100? anonymous comments
  - allow to specify the timeframe for the comments (with maximum? 2 weeks?)

> As a possible alternative, I suggest you edit the settings so that users that don't belong to the team can leave you comments: https://help.penpot.app/user-guide/view-mode/#viewmode-sharing

No, it is not the solution, because clients need the account anyway.

BTW: thank you for the great tool!
