### ISSUE TITLE
feature: Development without docker?

### ISSUE THREAD

**Issue by khoshrou** [uxbox/uxbox#2472]
### Is your feature request related to a problem? Please describe.

I like to run penpot without docker, is it possible?

### Describe the solution you'd like.

I like to run the code for front end and backend separately on my machine (windows or mac) without using docker. is this possible?
like open the code in VS Code and just run a npm script to start front end or back end
is there a helper guide for this?

**Comment by niwinz** [comment]
Docker files are open and are list of instructions to do. You can replicate whatever dockerfile builds and run the same commands; I mean there are nothing docker specific/locking on development environment that will prevent do it.

We use docker for development environment for have an uniform development environment, every person has the exact system to develop so we reduce the possible errors. But docker is used mainly to execute, the code and the editor lives on the user's host machine, in a shared directory with docker, so the user can be using the editor of its preference (on our team some people uses emacs, some vim, some VS Code...)

**But all of us, uses linux**, so this is not tested on other platforms, so we cant help you make it running on anything different that a linux distribution (this is another valuable reason to use docker, because it abstracts the devenv from the user operating system).
