### ISSUE TITLE
Standard Docker Compose file that works without hassle

### ISSUE THREAD

**Issue by prononext** [uxbox/uxbox#2644]
### Is your feature request related to a problem? Please describe.

The provided docker compose files on penpot should be working out of the box. 
Right now not one of them did work for me compared to other open source solutions that I just paste in container management solutions like portainer, edit the environment variables and go.  At max need to edit some version tags and its working. With penpot I have to copy and format all the variables from the non standard env file into the compose format and even then it is not working. Even if I get the elest.io compose file it will not work. Testing and contributing to the project is very hard in this case. 

### Describe the solution you'd like.

I would like a clean docker folder with two docker-compose.yaml files (one for http and one for https with traefik and automatic https). 

also 2 .env files (one for http and one for https with traefik and automatic letsencrypt https. 

All files, docker-compose and env should have demo variables wich should work out of the box without changing or editing. 

The compose file should contain the environment variables and not a link to a .env file so it is universal compatible in a standard docker workflow, which is just looking for a .env file and gets the needed variables from it which are before referenced in the docker-compose.yaml. 

### Additional context

I am following this project since the start and do like it very much. I have used a elest.io instance for a couple of month which was quite ok. As I like to scale and test it on self hosted infrastructure I have made several tries, each with several month between to set it up but have given up and did not use it anymore as the setup was not working. 

Using much more complicated compose setups than penpot which are working with the provided github ressouces without any problem, I hope penpot will find a solution for that, so that many more people can contribute and grow that increadible project. 

Thank you

**Comment by niwinz** [comment]
Hello @prononext, thanks for your time on making this proposal.

Lets take it by parts:
- The current docker compose works out of the box for the purpose it was created: running a penpot instance in local environment. I just checked it right now, and I was able to start new instance on localhost:9001, enter, register a new user, create file and draw some rectangles. So, from my point of view it works as expected.
- The **no standard** env file, is [pretty standard in docker compose](https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option). If it does not works outside compose, this not makes it non standard. Is just the tool/service you want to use does not support a pretty standard environment file (just a file containing environment variables, nothing new invented by docker compose). Additionally, it is used in this manner because some variables applies to multiple modules: frontend, backend and exporter; so for not repeating them and make the configuration more error prone is better use a single file for configuration.
- There are also here the debate between security and usability. If I put more unsafe settings by default that will facilitate some stuff other people will be concerned about that. This compose file is not intended to be used as-is for serving penpot to the public, it serves to run it on localhost (that is the real purpose), so if you need to run it under different domain and under https, you should put that on top of that. Want http, just use Caddy or Traefic on top of penpot; nothing in penpot prevents it accessing throught HTTPS, penpot will work out of the box, is just not penpot responsibility to setup https for you.
- We can't provide a configuration for every body, you want traefic, someone wants other thing, there are a lot of different needs and we can't solve all of them. Reminder, maintaining more files, more configurations also implies more time dedicate to test it (and so on). We are small team and right now we dedicate our time to develop the platform. We provide the basic building blocks for someone else can start and use it with a little bit of system/docker knowledge. If you don't know how to do it with docker, you can use services like Elestio as alternative.
- We know that we have some missing stuff for on-premise users, would be awesome to have admin panel for be able to create users and teams without using the standard register/invitation mechanism. We know that current approach does not scales, but we have plans to solve it. But time to time please, we can't do all the tings on same time.

Having said that, we will take your suggestion in consideration, I'm already working on this, to make this step a bit better that is right now. But the goals as I said previously is not to provide universal config for many environments. I will consider not using env file as you mention.

**Comment by bpmooch** [comment]
I agree with the sentiment, but I think a better answer than a one size fits all config, is an examples folder containing multiple configurations for different needs. For example, it's not clear to me from the docs how to properly configure github authentication as the only allowed authentication for a penpot install. A list of examples might include a `minimum.yaml` that is similar to the existing example configuration as well as other scenarios users might want. .@prononext do you have other example configurations that would be important to you?
