### ISSUE TITLE
enhancement: Content for Align options tooltip in Auto layout are confusing

### ISSUE THREAD

**Issue by iprithvitharun** [uxbox/uxbox#2963]
### Steps To Reproduce

1. Hover over the **Align** options under Auto Layout.
2. Tooltips will appear.

### Expected behavior

There are clear and straightforward content options, **Top** and **Bottom**.

Also, we don't have to repeat "items". We can just say,

* Top
* Center 
* Bottom

### Actual behavior

This behavior is confusing because **_start_** and **_end_** can mean different things based on context, culture, and geographic location.

For example, in terms of writing content (English) "start" means left and not top. Also in some East Asian languages, it can be written in the vertical and horizontal axis.

### Screenshots or video

<img width="222" alt="align end" src="https://user-images.githubusercontent.com/58725708/220163033-2be49e57-a7f3-475c-a495-8f21e28bd442.png">

<img width="219" alt="align start" src="https://user-images.githubusercontent.com/58725708/220163039-94d03e3f-ede7-4dc0-a8ad-e48b6d7689e7.png">

**Comment by ondrejkonec** [comment]
@iprithvitharun I think this is because it reflect [naming aligning items in CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Aligning_Items_in_a_Flex_Container) and I think it's important to keep naming like this.

When you change direction, the tooltip text is not changing. As you can see on the screen, now your suggestion "bottom" or "top" is not working. Maybe would be nice to call it "right" and "left", but that would mean creating a new variant of changing the tooltip (not just icons as it is right now). Another thing is, that you can again change direction to **reverse** and top/bottom/left/right is not working again.

You can check it here:
[Screen Recording 2023-02-21 at 3.25.05.webm](https://user-images.githubusercontent.com/28909808/220232450-baea0402-d516-44bf-b985-2073475516d5.webm)

**Comment by elhombretecla** [comment]
Hi @iprithvitharun thanks for your feedback :)

As @ondrejkonec said, we are using same CSS naming standards. Our approach is that designers and developers can finally work in unison. Using CSS code standards ensures that there are no errors when communicating between different roles.

**Comment by iprithvitharun** [comment]
@ondrejkonec Thanks for the explanation. TIL.

@elhombretecla This makes sense and is the right approach for Auto layout.
