### ISSUE TITLE
Install locally and run from localhost

### ISSUE THREAD

**Issue by lynxionxs** [uxbox/uxbox#2973]
Is there a way to just get the source code locally and just start a localhost server to run Penpot. Without Docker or the bloated Electron app?

**Comment by Alotor** [comment]
The easier way it's Docker because the application requires of several services to run (postgres, redis, etc) and there are several processes necesary to start the compilation process.

We recommend to use docker or host your instance in something like Elestio.

If you're determined to run "outside docker" you could always start the same services as the docker-compose file manually. But currently we don't provide any recipes to do so.
