### ISSUE TITLE
feature: Need more documentation of how to run Penpot with registration disabled

### ISSUE THREAD

**Issue by RobertBrown3** [uxbox/uxbox#3017]
### Is your feature request related to a problem? Please describe.

I would like to run my Penpot self- hosted system with registration disabled/ I would like to be able to add (or remove) user accounts for specific people.

There is the ability to set Penpit so that the registration is disabled. Unfortunately there is no documentation on how to add accounts or manage them with registration turned off. In the docker-compose.yaml file, there is a reference to "using an admin", but aside from that clue there is nothing on how to administer a Penpot installation.

### Describe the solution you'd like.

Adding documentation on how to manage users and/or administrate a Penpot application with registration turned off would be the best solution.

### Describe alternatives you've considered.

No other viable alternatives come to mind.

**Comment by bpmooch** [comment]
+1 to needing this. I would like to manually add users and prevent all authentication methods except for github. I am unable to figure out how to accomplish this.

**Comment by VVege** [comment]
+1

**Comment by niwinz** [comment]
Hello @RobertBrown3 sorry for the inconvenience.
Can you tell me where you read the documentation?

I mean, I honestly try to understand what problem have the current documentation, because after looking on it all information very quickly:

0. Look at the configuration page where is explained how to setup flags: https://help.penpot.app/technical-guide/configuration/#common
1. Followed by the `registration` section which explains what flags to use for disable registration: https://help.penpot.app/technical-guide/configuration/#registration you can see the
2. And then, go to the _authentication providers_ for see how to configure github auth.

Also, in the getting started guide you have an example on how to use `manage.py` script https://help.penpot.app/technical-guide/getting-started/#configure-penpot-with-docker

I agree that the last one looks like more dificult to find, and we will improve it. But it still documented on the "getting-started" section which I suppose everyone should read when intend to install penpot on premise.

Any feedback or improvement is very welcome and I will take in consideration all suggestions for improve the documentation and its structure.
