### ISSUE TITLE
feature: REST API for high level project/file/font/etc. management 

### ISSUE THREAD

**Issue by ile** [uxbox/uxbox#3154]
### Is your feature request related to a problem? Please describe.

As I'm thinking of integrating Penpot with my web app, I think I would like to use the look and feel of my app in the overview/main page and only use the actual design page (where the magic happens) in Penpot.

### Describe the solution you'd like.

For this I would need a REST API for Create/Read/Update/Delete (CRUD) for those high level objects.

I know that it already sort of exists, but the usage is a bit difficult, as the syntax is in Clojure's syntax. 

A simpler API would help a lot here.

**Comment by niwinz** [comment]
We are already working on exposing OpenAPI json (with swagger UI)

**Comment by niwinz** [comment]
In any case we don't going to reimplement our api using REST (because REST as is has no value for us). Our API is pretty simple: RPC, with no HTTP method involved (you can use GET or POST, as you prefer). All methods are under `/api/rcp/commands/<method-name>` that has input and output defined (which we want to expand to have full support of plain JSON input and output and OpenAPI specs)

**Comment by ile** [comment]
:+1:
