### ISSUE TITLE
feature: click instead of double click to edit file

### ISSUE THREAD

**Issue by ile** [uxbox/uxbox#3228]
### Is your feature request related to a problem? Please describe.

I would like to, and in the web I think it would make sense, to initiate "edit" for "file" by just clicking it, instead of double clicking. The same with the "more menu" (three dots).

### Describe the solution you'd like.

In the web double click isn't that common. Links and buttons are just clicked once.

### Additional context

![image](https://github.com/penpot/penpot/assets/433707/91360ab8-f2e0-440b-aa4b-208c599eba16)

**Comment by ile** [comment]
The moving of files can be handled with an appearing "handle" icon. 

https://icon-icons.com/icon/drag-handle-line/235648

**Comment by jdittrich** [comment]
I agree that double click in uncommon and single click is probably a better interaction here

The more menu opens with a single click for me, though

**Comment by soldior777** [comment]
fire fox 
Orion

**Comment by soldior777** [comment]
browsers firfox and Orion bugged my chrome

**Comment by madalenapmelo-kp** [comment]
Hi @soldior777,

Double click to open a file is a standard in file management since a single click is used to select items for further operations like editing, grouping, etc., not just opening the file. As such, this is not something that we plan to address in the foreseeable future.

In any case, thanks for the suggestion :slightly_smiling_face:
