### ISSUE TITLE
bug: Undo stack is inconsistent

### ISSUE THREAD

**Issue by NusryNizam** [uxbox/uxbox#3230]
### Steps To Reproduce

I cannot reproduce it. It is unpredictable. But it happend to me multiple times. 

Platforms: Brave on Ubuntu 22.10, Firefox on Ubuntu 22.10, Chrome on Windows 11

### Expected behavior

When undoing, the previous operation should be restored.

### Actual behavior

operations in the past are restored instead of the most recent one.

### Screenshots or video

https://github.com/penpot/penpot/assets/24385617/ccfccecb-f2e0-4214-acae-33482fb2cd62

### Desktop (please complete the following information)

- Ubuntu 22.10 - Brave - Version 1.51.114 Chromium: 113.0.5672.92 (Official Build) (64-bit)
- Ubuntu 22.10 - Firefox - Version 113.0.1
- Windows 11 - Chrome 113.0.5672.127 (Official Build) (64-bit)

### Environment (please complete the following information)

Both on self hosted and https://design.penpot.app

Self-hosted: Docker Compose version v2.17.2

**Comment by pabloalba** [comment]
Hi!

You are right, there are some glitches on the undo stack. We're looking into it, but as you said it's difficult to reproduce. I hope we can fix it soon.

**Comment by NusryNizam** [comment]
Thank you! Looking forward.

**Comment by soutiagojose** [comment]
With me, ctrl+z has unusual actions. I create an action and if I undo it, it doesn't undo it, but it undoes something else random (or not) within the project.
Example:
I created an artboard and inside there was a rectangle. I didn't intend to change the rectangle. I created an ellipse outside of the artboard, but I had to ctrl+z to restore an old change I made. The penpot restores what I did to the rectangle and keeps the ellipse the way it is. And if I try to go back, redo the change, of the rectangle, the penpot doesn't do it.

**Comment by superalex** [comment]
@allytiago could you please record a video with the sequence you did?, I'm trying to reproduce it but I can't

**Comment by soutiagojose** [comment]
> @allytiago could you please record a video with the sequence you did?, I'm trying to reproduce it but I can't

I will try. sometimes ctrl+z doesn't work, other times it works, it's a bit random

**Comment by stuartcusackie** [comment]
Yep. ctrl+z messes up my boards every time. Windows 10 Chrome.

**Comment by gpkc** [comment]
+1 for me, undo completely messes up my board and it very often results in lost work. Luckily I haven't lost hours of work, but that seems to be just because I try to police myself and not use the feature.

**Comment by moranda** [comment]
Same here on firefox + ubuntu 22.04:
- random actions cancelled
- broken redo
- lost work

**Comment by StaticBR** [comment]
Same on Windows and Firefox.

It is pretty annoying, if you can not undo your changes.

**Comment by TheHaymaker** [comment]
+1 

Using the cloud deployed version via Penpot.app, I've experienced this and it infringes on the UX to such an extent that I just give up and leave. Not trying to pile on here. My intention is to communicate how critical this is to workflows.

Thank you all for your efforts and work on this.

**Comment by pabloalba** [comment]
Hi! We recently found the source of some of the inconsistency with the undo stack. It's veeery tricky, but we're working on it. Don't lose hope! :)

**Comment by dw-0** [comment]
Came across this issue just a moment ago. It messed up everything and all elements on my board were suddenly gone. It also somehow managed to overwrite the full history so that i wasn't able to step back in time to restore anything. "Thanks" to the autosave feature, the broken state was instantly saved to make sure its basically gone forever. Lost ~4-5hrs of work.

Pretty much a dealbreaker, hence i gave up using penpot for now. I can't trust a software that randomly garbles hours of work without any option at all to recover it. Maybe consider adding a manual save function besides the autosave function which allows saving revisions of the project or something similar to give your users a chance to at least securely save their work in regular intervals.

**Comment by pabloalba** [comment]
Hi @th33xitus !

I'm so sorry. If you write to support@penpot.app with the link of the file, maybe we can revert it to a previous version.

**Comment by dw-0** [comment]
Hey @pabloalba !
Thank you for the kind offer, but i was using a self hosted Docker instance :)

**Comment by VVege** [comment]
+ 1
Penpot is overall very good, but I've also encountered an issue where using Ctrl+Z clears the document, which is truly maddening. Once it's auto-saved, a day's worth of work could be gone. I hope more manpower can be allocated to address this issue. Really, thank you so much!

**Comment by pabloalba** [comment]
Hi @VVege !

We've done a lot of improvements on the Ctrl+Z functionality, and it's much more stable now. If this has happened to you recently, we definitively want to know more in order to fix it.

Can you please write to support@penpot.app and give us all the info that you can? The url of the affected file, the operations that you were doing... anything that can help us to catch the problem.

Also, we probably can revert it to a previous version, so you can recover at leas part of your work!

Thank you

**Comment by VVege** [comment]
> Hi @VVege !
> 
> We've done a lot of improvements on the Ctrl+Z functionality, and it's much more stable now. If this has happened to you recently, we definitively want to know more in order to fix it.
> 
> Can you please write to [support@penpot.app](mailto:support@penpot.app) and give us all the info that you can? The url of the affected file, the operations that you were doing... anything that can help us to catch the problem.
> 
> Also, we probably can revert it to a previous version, so you can recover at leas part of your work!
> 
> Thank you

Alright, it's feedback from my users. Since it happens intermittently, there's no trace left. I've informed them to record a video if it occurs again. By the way, may I ask in which version you optimized the 'Ctrl Z' feature? I am currently using version 1.18.1. Should I consider updating to the latest version?

**Comment by pabloalba** [comment]
Yes! You definitively should update to the latest version. In particular in the 1.19 we resolve a looooong list of bugs. Check it here! https://github.com/penpot/penpot/releases

**Comment by madalenapmelo-kp** [comment]
Hi @NusryNizam ,

Could you please confirm if the issue is resolved and close this issue if it is indeed resolved?

Thanks!

**Comment by NusryNizam** [comment]
Yes, I don't see any issues now :)
