### ISSUE TITLE
bug: no stroke scale when setting new dimensions to a svg

### ISSUE THREAD

**Issue by NicolasLeboeuf** [uxbox/uxbox#3340]
### Steps To Reproduce

1. Import a svg
2. Enable "proportional scale"
3. Define new dimensions
4. The stroke isn't scaled

### Expected behavior

Like with the corner handle, the stroke should be scaled when setting a dimension.

### Actual behavior

The stroke doesn't scale.

### Screenshots or video

[Capture vidéo du 23-06-2023 10:16:36.webm](https://github.com/penpot/penpot/assets/62602652/8de797b2-5d38-4199-bdaa-8a15de23b554)

### Desktop (please complete the following information)

- Ubuntu 22.04
- Chrome 114

**Comment by EsterLatorre** [comment]
Hello Nicolas!
Thats an expected behaviour. If you want to scale proportionally you need to press the key "k" and you will see that the handlers are a bit different. Then size your shape manually so it takes up the space you want and this type of scaling will also scale the properties inside.
I hope that helped ;)

**Comment by NicolasLeboeuf** [comment]
Then it's not possible to resize correctly a svg by typing the aimed dimensions? Is it really the expected behavior? That makes no sense.

If you look at the video, I used the handlers (btw they don't change by typing K), but **I don't want to use the handlers**, it's painful (reducing a svg from 512 to 16, pixel-perfect), and the dimension fields are there for that.

Ok it's not a bug, but you could at least consider it as an enhancement: same behavior between the handlers and using the dimensions.
