### ISSUE TITLE
bug: disable-registration flag not working with docker

### ISSUE THREAD

**Issue by Nicolas-Derre-Cloudmefy** [uxbox/uxbox#3444]
### Steps To Reproduce

1. Download penpot docker.compose from git
2. Setup disable-registration flag in both, frontend and backend `- PENPOT_FLAGS=...`
3. Fresh local install of penpot via `docker compose -p penpot -f docker-compose.yaml up -d`
4. Open web interface on localhost:9001 and create any user you want at will

### Expected behavior

Not being able to create new users

### Actual behavior

The flag doesn't disable the creation of users from the web interface of penpot

### Environment (please complete the following information)

Self hosted:

-windows 11
-Docker Desktop 4.21.1 (114176)

**Comment by Nicolas-Derre-Cloudmefy** [comment]
yaml file uploaded as txt since git doesn't like yaml files to be uploaded
[docker-compose.yaml.txt](https://github.com/penpot/penpot/files/12158494/docker-compose.yaml.txt)

**Comment by Nicolas-Derre-Cloudmefy** [comment]
After creating some users with the `docker exec -ti penpot-penpot-backend-1 python3 ./manage.py create-profile` the user creation on the web interface seems to have been disabled.

**Comment by niwinz** [comment]
maybe that was a cache? I mean the create-profile command does nothing more that just create a user, so it is not a cause of disabling registration on interface.
Another question; when registration was still visible, Have you been able to use it to create users?

**Comment by Nicolas-Derre-Cloudmefy** [comment]
Yes, when it was still visible I was able to create users, thats why I didn't think it could be a cache related issue.

**Comment by niwinz** [comment]
> Yes, when it was still visible I was able to create users, thats why I didn't think it could be a cache related issue.

Ok, I will check it

**Comment by niwinz** [comment]
I have tested it with latest images and looks it works as expected. I have found other another issue related to browser cache. If you change the flags and restart the docker container, ensure the browser cache is cleared for properly see the flag applied.

In any case, the cache issue will be fixed

**Comment by starship-jr** [comment]
Hello, 
I am currently experiencing the same kind of issue with the script manage.py create-profile function.

I created a penpot instance with docker and installed with docker compose.
I let the enable-registration flag in the config

When I create a new account/singup through penpot client, it all works perfectly.

But when I create an account with the script manage.py create-profile it does not work.

I can see the user created with the python script in database, in the table profile, but the generated password is not hashed.
It only happens with the python script. It works normally with the UI and the password is hashed in this case

I think the problem comes from here.
