### ISSUE TITLE
bug: exporter not creating render file

### ISSUE THREAD

**Issue by RonElwaya** [uxbox/uxbox#3513]
### Steps To Reproduce

1. click export on frontend

### Expected behavior

object exported

### Actual behavior

object not exported
returns following error message.
upon clicking on the link in the logs i dont see anything and the /tmp/penpot directory is empty.

### Screenshots or video

![20230809_122812](https://github.com/penpot/penpot/assets/138373187/d76b8a68-de5b-422f-8404-ba58f0f2c8a0)

### Environment (please complete the following information)

exporter running on vm
rhel 8.4
official image version 1.18.4

**Comment by niwinz** [comment]
We have detected the same issue with multiple export.
A new images are in process of publication right now

**Comment by RonElwaya** [comment]
Is there a prohection to when they will be up? What will be their tag? Could you inform me when they go up?

**Comment by niwinz** [comment]
We updated the latest tag and the 1.19.0 tag with the new build

**Comment by RonElwaya** [comment]
i have updated my setup to the 1.19.0 image but i still get the same error

**Comment by RonElwaya** [comment]
will it be fixed?

**Comment by niwinz** [comment]
Hello @RonElwaya 
The underlying issue was fixed, right now it works as expected.
For ensure it, I have launched an clean instance using our docker-compose.yaml file and tested it. If you still get the error, I'm pretty sure it is related to configuration where I can't help you.

Looking on the captured screenshot, the exporter is requesting to http://localhost:9001, and if I suppose you are running it on docker using docker-compose file that we have provided, this value is wrong, I mean, it should be:
![image](https://github.com/penpot/penpot/assets/843689/1910ab67-c808-4b3a-9c2e-c37ca9c8d5d2)
