### ISSUE TITLE
feature: Libraries should not be visible in drafts

### ISSUE THREAD

**Issue by GreatestFool** [uxbox/uxbox#3666]
### Is your feature request related to a problem? Please describe.

When you add libraries, they should not appear in the user's `drafts`. They are not user-created, and no custom changes have been made to them. For them to appear in `drafts` implies that it is a user-created project, especially when the `libraries` section displays the very same ones, but without user-created projects.

It's confusing and just generally bad UX. And considering you cannot reorder them, as far as I've found, that makes it even worse when a user-created project ends up needing to be scrolled down to find instead of it being at the top.

### Describe the solution you'd like.

- Separate the contents of `drafts` and `libraries`.
- Keep libraries in `libraries` and user-created projects in `drafts`.
- If the user makes a change to a library, either show the library in both `drafts` and `libraries`.
    - Or ideally, make it a copy in `drafts`, where the original is available in `libraries` at all times.

### Describe alternatives you've considered.

There is no alternative to really consider here. It's either to improve upon the already existing solution, or keep using the original solution. It's not the end of the world, even though it's bad UX and likely frustrating for end-users to use.

### Additional context

This is how it looks now:
![image](https://github.com/penpot/penpot/assets/3003484/9d18db9b-c5b6-44d6-80dd-7d4c9f0313f2)

And by changing how the UI displays libraries, it should be like this:
- Drafts
![image](https://github.com/penpot/penpot/assets/3003484/35a0124f-ea55-4eac-bac0-49de87941e2c)

- Libraries:
![image](https://github.com/penpot/penpot/assets/3003484/28fe21e2-8477-4c5a-8fa5-33234a1357c9)

Though, as can be seen in the drafts image, there also really needs to be a better distinction between what is and what isn't a library in the first place. The little icon up in the top right corner of the thumbnails aren't good enough, because this isn't really obvious until after you download them in the first place. When you [go here](https://penpot.app/libraries-templates) to get more, there's no distinction at all. However, the UI icon for a library will be moot if the changes are implemented where libraries are separated from drafts. Though, considering how there are also templates, it would perhaps be good to have a section separate from `libraries` and `drafts` dedicated only to templates. That isn't an uncommon choice in design software like this, from what I can remember.

**Comment by elhombretecla** [comment]
Hi @GreatestFool thank you so much for your feedback :)

By default, libraries downloaded from the dashboard carousel are added to "Drafts" because it's the only "default" project that every user has. However, users have the flexibility to organize their files as they see fit.

As demonstrated in the example image you provided, libraries can be moved to other projects. We've designed it this way to empower users to decide and organize their files according to their preferences. Additionally, it's important to note that once a library or template is downloaded, it becomes a 100% editable copy for the user.

![image](https://github.com/penpot/penpot/assets/1045247/f6614753-bde5-47fb-b297-216f1e45c37b)

![image](https://github.com/penpot/penpot/assets/1045247/947041a7-d52b-4369-91a2-ece9abb115f5)

We understand your concerns about the user experience and the inability to reorder projects. We'll take your feedback into consideration as we continue to improve Penpot.

**Comment by GreatestFool** [comment]
Not how I would do, but decent enough I suppose. I'll leave it up to you to close this, I'm not sure if you'd like to keep this open as reference or not. But otherwise feel free to close this issue.
