### ISSUE TITLE
bug: cropped API response JSON body for huge Penpot files (>150000 lines)

### ISSUE THREAD

**Issue by roberto-red** [uxbox/uxbox#3670]
### Steps To Reproduce

1. Generate an access token
2. Import the "Tutorial for beginners" `.penpot` file from https://penpot.app/libraries-templates
3. Make a HTTP POST call to the Penpot API for the `get-file` RPC specifying:
   - an `Authorization: Token YOUR_ACCESS_TOKEN` header
   - an `Accept: application/json` header
   - a `Content-Type: application/json` header
   - the correct `id` param in the body object

### Expected behavior

Receive a response with `200` HTTP code and a properly formatted JSON body.

### Actual behavior

The response has a `200` HTTP code and the body is a cropped, invalid JSON (mind the white-space):

```
					"187ee84f-c56d-8067-8002-5f0236eb7c6c": {
						"y": 1775.043,
						"rotation": 0,
						"name": "icon-keyboard (1)-1",
						"width": 18,
						"type": "group",
						"svgAttrs": {
							"width": "71.071",
							"height": "54.071",
							"style": {
								
```

### Environment (please complete the following information)

- Host: https://design.penpot.app
- Penpot version: 1.19

### Additional context

Example call using `curl` and `jq`:

```
ACCESS_TOKEN="your-access-token-here"
FILE_ID="your-file-id-here"

curl --request POST \
  --url https://design.penpot.app/api/rpc/command/get-file \
  --header 'Accept: application/json' \
  --header "Authorization: Token $ACCESS_TOKEN" \
  --header 'Content-Type: application/json' \
  --data "{
        \"id\": \"$FILE_ID\"
}" | jq '.'
```

> jq: parse error: Unfinished JSON term at EOF at line 155013, column 25

**Comment by pithyless** [comment]
Hi there Penpot team! I hope you don't mind some drive-by bug analysis. :)

I was hoping to familiarize myself a little with the API, so I tried to reproduce and track down the source of this bug.

Based on the description, my initial hypothesis was that this sounds like a buffered stream being cut off early before it can flush all of its data. I even suspected it might be related to the pretty-printing that is enabled by default.

I managed to reproduce the bug locally via the dev docker setup (kudos to @roberto-red  for the detailed info). Nevertheless, it looks like the problem is not with buffered/streaming data, but with custom serializers. Digging further, there are multiple places in the codebase that register custom serialization handlers for `fressian` and `transit` to deal with custom records, but this does would not help when encoding json via `jsonista` in `app.http.middleware/wrap-format-response`. The suggested payload in this bug report ("Tutorial for beginners") is problematic not due to the size of the payload, but because it includes custom non-serializable records (eg. `app.common.geom.matrix.Matrix`).

The bug as reported (invalid JSON output) is a separate, but related issue, due to the error handling in `wrap-format-response`:

```
          (json-streamable-body [data]
            (reify rres/StreamableResponseBody
              (-write-body-to-stream [_ _ output-stream]
                (try
                  (with-open [^OutputStream bos (buffered-output-stream output-stream buffer-size)]
                    (json/write! bos data json-mapper))

                  (catch java.io.IOException _)
                  (catch Throwable cause
                    (binding [l/*context* {:value data}]
                      (l/error :hint "unexpected error on encoding response"
                               :cause cause)))
                  (finally
                    (.close ^OutputStream output-stream))))))
```

The exception thrown in the case of the serialization error is `com.fasterxml.jackson.databind.JsonMappingException`, which is a subclass of `java.io.IOException`. It is being caught by the first catch statement and being silently ignored. Given the logging error of the `Throwable` catch, I don't think this was by design. And since the response body is being eagerly written to by jackson/jsonista and cleanly closed, we end up with an incomplete payload on the wire and no logs or other indication that anything went wrong.

If my analysis is valid (disclaimer: I am unfamiliar with the codebase), it raises a few thoughts and next steps:

1. The app uses `transit+json` internally, so this may have been overlooked for some time. If JSON is not fully supported at the moment, perhaps it should be removed as valid content-type in the RPC api? Otherwise, does it need similar custom serialization handlers like fressian and transit?
2. The exception handlers in the response middleware may need to be reordered to correctly deal with encoding errors. Otherwise, this will hurt further debugging of other encoding related errors.
3. Perhaps this is a non-issue, but I was surprised json pretty-printing was enabled for these large payloads by default. Has someone confirmed this no significant impact on performance? Otherwise, may be easy way to improve server latency.

I'm happy to look into this further, but wanted to get some feedback from the team before going down some unnecessary rabbit holes.

**Comment by ymolists** [comment]
Hi folks

This issue is happening to me with the get-file endpoint on the penpot cloud instance. Can anyone suggest a work around please ? 

Best Regards

**Comment by sneko** [comment]
Hi,

Same as for @ymolists (using a sample document with only a rectangle), when reaching `get-file` the JSON response content is cropped. In my case my client is in JavaScript so it's easier for me to deal directly with "raw" JSON structure instead of dealing with "transit format" (https://github.com/cognitect/transit-format).

What I can tell:
1. If using the request header `Accept: application/json`, the content is cropped (raw JSON format) : `{ "features": [`
2. If using the request header `Accept: */*` it will return the **entire** content in the Transit format: `[ "^ ", "~:features", ...` (I did not find a library to convert it easily to raw JSON so I prefer to wait for a fix)

I first thought about the `Transfer-Encoding: chunked` header but it works well even with it for the Transit format... Any idea @niwinz ?

I'm not sure but could it be related to https://github.com/penpot/penpot/issues/3546 ?

**Comment by niwinz** [comment]
https://github.com/penpot/penpot/pull/4760 should fix the issue of json truncation
