### ISSUE TITLE
bug: Flex layouts don't flex 😩: 

### ISSUE THREAD

**Issue by Panini-Manganini** [uxbox/uxbox#3912]
### Steps To Reproduce

1. Press T and create textbox
2. Write text inside textbox
3. Select textbox and press shift+a to turn it into a flex layout
4. Write inside textbox

### Expected behavior

I expected the flex layout to expand/shrink as I add/remove text from the textbox

### Actual behavior

Neither the board nor the textbox reacts in any way to addition or removal of text from the textbox.

### Screenshots or video

https://github.com/penpot/penpot/assets/153460250/fa16971e-5add-48f7-9fb3-6902cf446459

### Desktop (please complete the following information)

- Windows 10
- Chrome 120.0.6099.71

### Environment (please complete the following information)

https://design.penpot.app/

### Additional context

I have followed 3 tutorials step by step and this bug occurred every time.

**Comment by madalenapmelo-kp** [comment]
Hi @KemamSermala,

The text box is not automatically adjusted because in the **Text** options the sizing is set to _Fixed_ (see screenshot below).
![Screenshot from 2023-12-12 12-19-37](https://github.com/penpot/penpot/assets/144885032/e553efa6-752a-4c2c-976c-4b9dc1483a9f)

If you select the option _auto height_ or _auto width_, the text box will adjust as you add text.

You can find more details about the Text options in the official documentation here: https://help.penpot.app/user-guide/objects/#text

**Comment by Panini-Manganini** [comment]
Thanks @madalenapmelo-kp... sorry for the silly question
