### ISSUE TITLE
bug: 유니코드로 페이지 작성시 IME 문제로 화면에 출력되기 전에 다른 엘리먼트를 선택시 gitpot 에러 페이지로 넘어감

### ISSUE THREAD

**Issue by ydwhoru** [uxbox/uxbox#4062]
### Steps To Reproduce

테스트 방법
1. 특정 텍스트 입력 창을 만든다
2. 유니코드 텍스트 입력 후(화면에 출력 되지 않은 상태로) 다른 엘리먼트를 활성화(클릭) 시킨다
3. 에러로 인한 다른 페이지 이동이 일어난다

### Expected behavior

고쳐야 할것같습니다.

### Actual behavior

웹에서 IME에러 왜 에러가 나는지 모르겠음

### Desktop (please complete the following information)

window 11

### Smartphone (please complete the following information)

chrome

### Environment (please complete the following information)

self host

**Comment by ydwhoru** [comment]
혹시 이 글을 보면서 이슈 변화가 생겼을 때 메일 혹은 기타 커뮤니티로 알림 주는 방법을 알면 공유해주시면 감사하겠음.
ydwhoru@gmail.com

**Comment by madalenapmelo-kp** [comment]
Hi @ydwhoru,

Would you be able to share a screen recording of this behavior?

**Comment by ydwhoru** [comment]
i sent email, did you received?

**Comment by madalenapmelo-kp** [comment]
@ydwhoru we didn't receive the email, could you please confirm that you sent it to support@penpot.app?

**Comment by ydwhoru** [comment]
https://github.com/penpot/penpot/assets/8079891/bc4d354e-2d5f-4ee1-a8c4-8a427343bc7d

**Comment by madalenapmelo-kp** [comment]
Hi @ydwhoru,

This is a known issue that we intend to fix in the future, however, because it requires some rework this is not something that we can prioritize at the moment.

We have an [issue in our backlog on Taiga](https://tree.taiga.io/project/penpot/issue/6999) so that we can work on this at a later date.

I'm closing this issue here as this is already being tracked on https://github.com/penpot/penpot/issues/4163.
