### ISSUE TITLE
bug: The program crashes when hitting the space bar while using Chinese input method to insert text.

### ISSUE THREAD

**Issue by yehao1991** [uxbox/uxbox#4449]
### Steps To Reproduce

Create a new document -- Select text -- Input Chinese using a Chinese input method -- Press the space bar to confirm.

### Expected behavior

Fix this bug.

### Actual behavior

The program crashes when hitting the space bar while using Chinese input method to insert text.

### Screenshots or video

https://github.com/penpot/penpot/assets/158235386/25085cb5-26c1-428d-8788-57caded790b7

**Comment by yehao1991** [comment]
Environment：ubuntu 22.04 Docker Compose  v2.26.1

**Comment by madalenapmelo-kp** [comment]
Hi @yehao1991,

This is a known issue that we intend to fix in the future, however, because it requires some rework this is not something that we can prioritize at the moment.

We have an [issue in our backlog on Taiga](https://tree.taiga.io/project/penpot/issue/6999) so that we can work on this at a later date.

I'm closing this issue here as this is already being tracked on https://github.com/penpot/penpot/issues/4163.
