### ISSUE TITLE
bug: 无法插入中文

### ISSUE THREAD

**Issue by AhDEV-free** [uxbox/uxbox#4475]
### Steps To Reproduce

1. 打开一个新的Board
2. 按T输入文字
3. 当前输入法为中文
4. 输入中文后崩溃
5. 输入英文正常，且输入英文后再输入中文正常

### Expected behavior

正常输入中文

### Actual behavior

无法直接输入中文到文本框中

### Screenshots or video

<img width="1741" alt="image" src="https://github.com/penpot/penpot/assets/57929887/dff7deb1-af86-47bf-92cd-f48eb5c246db">

### Desktop (please complete the following information)

macos 
penpot installed with docker

**Comment by fengchuanBIG** [comment]
大佬你部署的时候  能不能局域网访问呢, 我更新到2.0后发现 局域网无法进行登录，

**Comment by AhDEV-free** [comment]
可以的，正常网络通，防火墙记得检查一下；


看一下日志是否正常启动；

**Comment by AhDEV-free** [comment]
@madalenapmelo-kp  你好，这个问题遇到过吗？
在chrom浏览器访问异常报错，无法插入中文；但是在Safari浏览器又是正常的；
<img width="1733" alt="image" src="https://github.com/penpot/penpot/assets/57929887/88a6b4a0-e7e8-4c83-93de-71be7709a4ce">

**Comment by madalenapmelo-kp** [comment]
Hi @AhDEV-free,

I believe this is related to a known issue that we intend to fix in the future, however, because it requires some rework this is not something that we can prioritize at the moment.

We have an [issue in our backlog on Taiga](https://tree.taiga.io/project/penpot/issue/6999) so that we can work on this at a later date.

I'm closing this issue here as this is already being tracked on https://github.com/penpot/penpot/issues/4163.
