### ISSUE TITLE
bug: 不能输入中文

### ISSUE THREAD

**Issue by Kev1nT** [uxbox/uxbox#4534]
### Steps To Reproduce

输入中文会导致报错

### Expected behavior

输入中文会导致报错

### Actual behavior

输入中文会导致报错

**Comment by madalenapmelo-kp** [comment]
Hi @Kev1nT,

This is a known issue that we intend to fix in the future, however, because it requires some rework this is not something that we can prioritize at the moment.

We have an [issue in our backlog on Taiga](https://tree.taiga.io/project/penpot/issue/6999) so that we can work on this at a later date.

I'm closing this issue here as this is already being tracked on https://github.com/penpot/penpot/issues/4163.
