### ISSUE TITLE
feature: ScrollTo Interaction for Prototypes

### ISSUE THREAD

**Issue by jdittrich** [uxbox/uxbox#4564]
### Is your feature request related to a problem? Please describe.

I would like to be able to prototype interactions that trigger not a navigation to a new board but a scroll to a position in the current board. 

### Describe the solution you'd like.

A scrollTo interaction similar to the one in figma

### Describe alternatives you've considered.

One can copy the board and move the content to simulate scrolling. 

### Additional context

This is based upon the question [“Scroll to” in prototypes (anchor links)](https://community.penpot.app/t/scroll-to-in-prototypes-anchor-links/5340) by PenPot-Community user [ValTOP](https://community.penpot.app/u/ValTOP).

**Comment by madalenapmelo-kp** [comment]
Hi @jdittrich,

Thank you for the suggestion! We already have this feature planned into our backlog but it hasn't been prioritized yet, you can find it on Taiga here: https://tree.taiga.io/project/penpot/us/4519. I've linked this issue as well as the community post there so that hopefully we can prioritize this soon!

I'm closing this issue as there is already https://github.com/penpot/penpot/issues/4438 where this is being tracked as well.
