### ISSUE TITLE
feature: storing files and thumbnails in filesystem instead of DB

### ISSUE THREAD

**Issue by pouya-abbassi** [uxbox/uxbox#4613]
### Is your feature request related to a problem? Please describe.

I'm running PenPot for a few months on AWS and noticed that my S3 is only 230 MB, while database dump is 1.1 GB.
I looked inside and sow these tables have blobs of data stored in their `data` column:
```
file
file_change
file_object_thumbnail
file_thumbnail
```
And I feel like these data could be stored in S3 for cleaner DB, faster lookup and less resource usage.

Is there a reason for storing these SVG/blobs/base64 data in the DB?
Can I do something (maybe a set a flag I didn't know) to put them in the S3?

### Describe the solution you'd like.

I'd like to store files and their thumbnails in the S3 instead of PostgreSQL.

**Comment by niwinz** [comment]
Hello @pouya-abbassi 

Using the file system for the cases you mention is a good option only when penpot runs on a single computer. But that obviously limits its scaling a lot and in a SAAS environment like the one in which design.penpot.app is running that is not very viable.

There is also the option of using shared storage such as S3, but that would mean that files with a high frequency of updates (several hundred updates per day) may incur additional costs since AWS S3 or similar charges for space and per operation. On small scales that is reasonable but when you scale a lot it is not. In addition, this will incur quite considerable additional latency.

With this said, we have in mind for the next versions to develop a system that analyzes the use of files and downloads from the database these blobs of files that are no longer updated frequently and places them in the storage system (S3 or of files, depending on the configuration of the instance in question). Thus lightening the table of files that are not being used frequently.

**Comment by henri9813** [comment]
Hello @niwinz ,

Does this improvement is mentioned in a Github issue ? 

In my opinion, you permit Penpot self hosting, but people can easily setup a MinIO to have a local s3. 

Storing files in database also have a huge cost when we deploy Penpot database inside a Cluster. 

NFS and S3 are designed to store files
Database is designed to store data, using a database to store blob / files is just an easy path to avoid ti find a real solution in my opinion.



Best regards,
