### ISSUE TITLE
bug: Penpot doesn't work properly in Arc Browser

### ISSUE THREAD

**Issue by sidbxl** [uxbox/uxbox#4614]
### Steps To Reproduce

1. Open Arc Browser on Windows.
2. Open any Penpot Project.
3. Drag & drop any component to the workspace.

### Expected behavior

1. Drag & drop the component to the workspace.
2. The component actualy drops.

### Actual behavior

The component doesn't drop.

### Screenshots or video

Video: https://github.com/penpot/penpot/assets/11022440/0ac0e1f2-f81b-4228-a0b3-7a9a092973dd

### Desktop (please complete the following information)

- OS: Win11
- Browser: Arc Browser latest.

### Environment (please complete the following information)

- Host: design.penpot.app

**Comment by madalenapmelo-kp** [comment]
Hi @sidbxl,
 
Thank you for reporting this! At the moment we provide support to the following browsers and I would recommend switching to one of these when working with Penpot:
- Chrome (or Chromium/Blink based browsers/Edge)
- Firefox
- WebKit (Safari / Epiphany)

I have shared this issue internally so that we can consider adding support to Arc in the future, but in the meantime I'm closing this issue as this is not planned.

Thanks!
