### ISSUE TITLE
feature: desktop version

### ISSUE THREAD

**Issue by henri9813** [uxbox/uxbox#4679]
### Is your feature request related to a problem? Please describe.

Penpot is very slow on safari (ok why not, safari is not good ), so I use firefox for penpot ( and I use firefox ONLY for penpot).

### Describe the solution you'd like.

I would like to have a desktop app such draw.io does instead of going to a webbrowser., I have an application on my MacBook called draw io and that's cool to stay focus on task. the desktop app run an electron app, so, it's the same code.

**Comment by SimplyPhy** [comment]
Discussion has been ongoing regarding this for years both in [this discussion thread](https://github.com/penpot/penpot/discussions/475) and elsewhere.

In my opinion, the lack of a 1st class downloadable version of Penpot is its single biggest obstacle for early adopters.  While I deeply respect the [work by Korbs on his Penpot Desktop Project](https://community.penpot.app/t/penpot-desktop-project/1468), it's not enough.  Furthermore, it hasn't worked for MacOS since Penpot 2.0 was released.

In my opinion, either Penpot should support Korbs's work directly and link/host the downloadables on the Penpot homepage, or a new solution is required and ought to be a very high priority, unless the Penpot team has reasons to specifically want to reduce adoption at this stage of development.  Either way, I've personally been very discouraged by the responses either pointing would-be users to Korbs's project, or dismissing this feature request as being outside of their area of concern.

In other news, @henri9813 the Penpot team has been vocal about recommending that users use Chrome for optimal performance and stability.  You can also "Install Page as App", as shown in my screenshot, which removes part of the Chrome interface, and lets you add Penpot to your Launchpad/Dock for easy access (nice for using Spotlight Search).  That said, you can't use tabs (well, you sort of can, but it's awkward) or hotkeys with this, and technically it's just a quicklink to Chrome minus the URL bar, more or less.

![image](https://github.com/penpot/penpot/assets/7506223/2611d5b4-d5de-4b38-ba78-42508032324d)

**Comment by madalenapmelo-kp** [comment]
Hi @henri9813,

There is already a Penpot Desktop Project developed by the Community - you can find more information on it in this [Community post](https://community.penpot.app/t/penpot-desktop-project/1468)!

**Comment by madalenapmelo-kp** [comment]
Hi @henri9813,

Thanks for the suggestion - as @SimplyPhy pointed out, this is an [ongoing discussion](https://github.com/penpot/penpot/discussions/475) and there is already a [Community-developed option](https://community.penpot.app/t/penpot-desktop-project/1468) available :slightly_smiling_face: 

I'm closing this issue as exploring this further is not a priority for us at the moment.
