### ISSUE TITLE
bug: OIDC auth not working after update to 2.1.0

### ISSUE THREAD

**Issue by dani** [uxbox/uxbox#4885]
### Steps To Reproduce

Just upgraded from 2.0.0 to 2.1.0, and I can't get my OIDC auth to work anymore. Get the error auth-provider-not-allowed. I'm using a private OIDC server, configured as:

```
PENPOT_OIDC_BASE_URI=https://portal.lapiole.org/oauth2
PENPOT_OIDC_USER_URI=https://portal.lapiole.org/oauth2/userinfo
PENPOT_OIDC_AUTH_URI=https://portal.lapiole.org/oauth2/authorize
PENPOT_OIDC_TOKEN_URI=https://portal.lapiole.org/oauth2/token
PENPOT_OIDC_SCOPES="openid email profile"
PENPOT_OIDC_CLIENT_ID=penpot
PENPOT_OIDC_CLIENT_SECRET=XXXXX
```

With flag enable-login-with-oidc on both backend and frontend. When I try to login via OIDC, I get this error (in french):
![image](https://github.com/user-attachments/assets/4c3b2aed-c935-4202-abcc-231c04d3059b)

Logging with LDAP (as I have both LDAP and OIDC configured) is working.

### Expected behavior

OIDC auth should work as before :-)

### Actual behavior

OIDC auth is broken

### Additional context

I see there have been changes in OIDC auth handling here : https://tree.taiga.io/project/penpot/us/7094
But I couldn't find any info in [the doc](https://help.penpot.app/technical-guide/configuration/#authentication-providers) regarding which provider are trusted and how to mark my own private provider as trusted

**Comment by dani** [comment]
I can get OIDC working again by changing the auth_backend to "oidc" for all users in the profile table (some initially logged in with ldap, some with oidc, only those with ldap were having problems)

**Comment by niwinz** [comment]
Similar or probably the same issue as https://github.com/penpot/penpot/issues/4882, will look on it soon

**Comment by niwinz** [comment]
For make the OIDC provider trusted, it should provide the `email_verified` prop/claim as `true`, this will allow login with LDAP and OIDC indistintrly to users that first logged-in/registered with LDAP.

**Comment by niwinz** [comment]
What happens is the following:

These users you mention have initially signed up via LDAP, and that has assigned the auth_backend property with the value ldap. When that profile is trying to log-in via OIDC, that OIDC provider is not reporting the claim email_verified, so penpot cannot trust that this provider has the email validated.

This is a security measure so that a profile registered via a specific backend is not impersonated by some OIDC backend that does not require email verification, as for example happens with the github backend.

I know that in on-premise this is not a common issue, but that is a security measure.

Therefore, the best solution to this problem is to try to modify or contact someone who manages your OIDC provider and ensure that the claim email_verified is sent with a true value in the authentication process. If that is not possible, we will look for other solutions.

**Comment by dani** [comment]
Thanks, the email_verified claim was the missing bit. I'll add this claim on my oidc service.
