### ISSUE TITLE
Performance Issue: Unable to navigate or edit large files

### ISSUE THREAD

**Issue by imre-gi** [uxbox/uxbox#4947]
### Steps To Reproduce

We are importing files from Figma to migrate to PenPot. The task is becoming impossible, as the large projects we have cannot be viewed as the app keeps crashing or freezing. 

I cannot share publicly the file, but I'm ok sharing in a private conversation.

### Expected behavior

I can access, navigate and edit large projects with ease

### Actual behavior

The app freezes or crashes when opening large project files

### Screenshots or video

https://www.loom.com/share/e13669390e604405b42d45e0e528c867?sid=064df934-440c-471d-8212-6564cf2538e1

### Desktop (please complete the following information)

- Windows 11
- Chrome Version 127.0.6533.89

**Comment by madalenapmelo-kp** [comment]
Hi @imre-gi,

Thank you for reporting this! Unfortunately, this is a known issue that requires extensive rework, which is why we haven't been able to prioritize it yet.

For the time being, please consider dividing your work into more files and more pages to improve the performance.

We apologize for the inconvenience caused, and we hope to be able to address this soon.

**Comment by imre-gi** [comment]
Hi @madalenapmelo-kp, 

thanks for the reply. 

Unfortunately, it's already divided into pages, and we cannot split it further or into files.

Is this rework something that will happen this year, or are you targeting 2025?

So we are aware that is not planned for the short or medium term and we'll try to find a suitable solution that allows us to work on Penpot.

**Comment by madalenapmelo-kp** [comment]
At the moment, we do not have an estimation for when this rework will happen, but it is something that we are actively discussing.
