### ISSUE TITLE
feature: Are there any plans to integrate Figma and sketch import and export functions?

### ISSUE THREAD

**Issue by SunilWang** [uxbox/uxbox#4962]
### Is your feature request related to a problem? Please describe.

Are there any plans to integrate Figma and sketch import and export functions?

### Describe the solution you'd like.

penpot is simply too powerful. But we have a lot of historical assets from Figma and sketch that are not available in penpot. Support for import or export would be great.

**Comment by myfunnyandy** [comment]
We're working on a plugin to export files from Figma to Penpot which is in a pretty advanced stage. In fact, it is already useful for some use cases. However, it still cannot export large files because of browser rendering limitations, an issue we are working on right now and that we intend to have fixed very soon.

You can already try it here https://www.figma.com/community/plugin/1219369440655168734/penpot-exporter
