### ISSUE TITLE
bug: black top header in full screen view mode and does not scale properly

### ISSUE THREAD

**Issue by Deewens** [uxbox/uxbox#5192]
### Steps To Reproduce

1. Create multiple slides (boards)
2. Open view mode
3. Open full screen view mode

### Expected behavior

Fullscreen mode should be fullscreen without a black top bar on top, and it should scale properly without scrollbar.

### Actual behavior

There is a black header bar on top of the view mode, and it does not scale properly (there are scrollbar). This should scale according to the screen ratio (my boards are 1080x1080p).

### Screenshots or video

![Screenshot from 2024-10-22 12-28-50](https://github.com/user-attachments/assets/3cd67b6a-356d-44d8-a183-0bdccf4190c1)
![Screenshot from 2024-10-22 12-28-59](https://github.com/user-attachments/assets/bb456044-196c-42a8-aac1-98a1c4d669a3)

### Desktop (please complete the following information)

- Linux (Linux Mint 22)
- Browser : Firefox, Zen Browser, Brave.

### Environment (please complete the following information)

https://design.penpot.app/

**Comment by madalenapmelo-kp** [comment]
Hi @Deewens,

Thanks for reporting this! While we haven't been able to prioritize this yet, we already have an issue in our backlog to look into it, you can find the details here: https://tree.taiga.io/project/penpot/issue/7723

I'm closing this issue here as we're already tracking this at #4567 :slightly_smiling_face:
