### ISSUE TITLE
feature: Typography: Allow for PX, PT, EM as font sizes and line height sizes

### ISSUE THREAD

**Issue by anditosan** [uxbox/uxbox#5274]
### Is your feature request related to a problem? Please describe.

Having only ratios in line height makes it so that I have to use external tools to calculate the appropriate ratio for my new typographies.

### Describe the solution you'd like.

The system should be able to accept standard font sizes and recalculate the size to the standard PenPot uses.

**Comment by madalenapmelo-kp** [comment]
Hi @anditosan,

Thank you for the suggestion! We already have a task in our backlog for this, you can find the details here: https://tree.taiga.io/project/penpot/us/4419?backlog-q=measure&no-milestone=1 :slightly_smiling_face: 

In the meantime, I'm closing this issue here as this is already being tracked at issue #3639

**Comment by emue-01** [comment]
Hi @madalenapmelo-kp, it seems the Taiga task only mentions adding support for relative units. As of now, I can't use plain old pixels in line height, only a ratio, as described by @anditosan. [User docs specifies line-height takes pixel values](https://help.penpot.app/user-guide/objects/#text) but when I enter for example 28px it just reverts back to default 1.2 ratio. If I just enter 28 it applies a ratio of 28, which is not ideal. 
I think it's a pain point for anyone working with spacing scales to maintain virtual rhythm and alignment.
Am I missing something?
