### ISSUE TITLE
feature: Recieve comments from Clients without the need to create an account

### ISSUE THREAD

**Issue by MrMK0R** [uxbox/uxbox#5323]
### Is your feature request related to a problem? Please describe.

When requesting feedback from clients, I often get more questions about account creation than the design itself. They typically only use Penpot once or twice, and not again unless a new project begins.

### Describe the solution you'd like.

The ability to share a special link that provides the client with direct access to the design, allowing them to leave comments without needing to create an account.

A prompt could appear before the link is opened, asking 'What's your name?' and using their response as the name for their comments. (This is similar to a feature in some WordPress applications).

### Describe alternatives you've considered.

Currently, I create a single account with a fake email for clients to sign into, then provide them with the login details and direct them to the designs for feedback.

**Comment by madalenapmelo-kp** [comment]
Hi @MrMK0R,

Thanks for the suggestion! This is something that we have considered in the past but have not yet been able to prioritize due to its' complexity.

I'm closing this issue as there is a [topic to discuss this in our Community](https://community.penpot.app/t/what-about-anonymous-comments-on-penpot-shared-prototypes-and-designs/2589?u=myfunnyandy) and this is already being tracked at issue #2934 :slightly_smiling_face:
