### ISSUE TITLE
feature: mobile penpot version

### ISSUE THREAD

**Issue by BDVGitHub** [uxbox/uxbox#5398]
### Is your feature request related to a problem? Please describe.

Its hard to use Penpot on an phone or tablet to vieuw an project.

### Describe the solution you'd like.

Is it possible to create an mobile version of the website? So its easier to view an project on a mobile device like an phone or tablet?

**Comment by madalenapmelo-kp** [comment]
Hi @BDVGitHub,

Thanks for the suggestion! This is something that has already been requested in the past but unfortunately, we haven't been able to prioritize it so far nor is it something we expect to prioritize in the near future.

I'm closing this issue here as there is already another issue open for this, #2266. I would also recommend participating in the discussions at the Community, there are already some topics about this option there and even an experimentation: https://community.penpot.app/t/mobile-app-experimentation-demo/2155 :slightly_smiling_face:
