### ISSUE TITLE
bug: Unable to get distances and measurements

### ISSUE THREAD

**Issue by BDVGitHub** [uxbox/uxbox#5401]
### Steps To Reproduce

Open an Penpot library file in Google Chrome.
Go to layers, select an object. (no bleu dashed lines to see)
Select an other object on the screen, no measurements shown

### Expected behavior

[Penpot user guide inspect](https://help.penpot.app/user-guide/inspect/)
See chapter "How to get distances and measurements"

### Actual behavior

I'm unable to easily get measurements and distances between an object and other objects or board edges.

### Screenshots or video

https://github.com/user-attachments/assets/4c712c26-748f-477a-9f5b-777ddd32da62

### Desktop (please complete the following information)

Chrome Version 131.0.6778.86 (Official build) (64-bits)

**Comment by madalenapmelo-kp** [comment]
Hi @BDVGitHub,

That section of the User Guide applies specifically to the Inspect mode, so those are the steps to see the distances and measurements after you select the tab **Inspect** on the right sidebar.

Since you are in Design mode, you can see the distances and measurements by selecting an object, clicking **Alt** and hovering over other objects :slightly_smiling_face:
